import asyncio
import json
import re

# Autogenerated gRPC wrappers
# Internal sandbox executor function
from rlef.reward import execution_reward

# inside your HighSpeedRewardServicer class...


async def _score_sample(
    self, prompt: str, completion: str, metadata_json: str
) -> float:
    code_match = re.findall(r"```python\s*(.*?)\s*```", completion, re.DOTALL)
    if not code_match:
        return 0.0

    extracted_code = code_match[-1]

    # Dynamically unpack the precise test assertions bound to this specific sample sequence
    try:
        meta = json.loads(metadata_json)
        inputs = meta.get("inputs", [])
        outputs = meta.get("outputs", [])
        fn_name = meta.get("fn_name", None)
        difficulty = meta.get("difficulty", "interview")
    except Exception:
        # Secure fallback if metadata is corrupted
        return 0.0

    loop = asyncio.get_running_loop()
    try:
        eval_result = await loop.run_in_executor(
            None,
            lambda: execution_reward(
                code=extracted_code,
                inputs=inputs,
                outputs=outputs,
                fn_name=fn_name,
                current_turn=2,
                difficulty=difficulty,
                ablation_cfg={
                    "use_lint_bonus": self.use_lint_bonus,
                    "use_multi_turn": True,
                },
            ),
        )
        score = eval_result.pass_rate

        if self.use_lint_bonus and "<tool>" in completion:
            score += 0.05

        return float(score)
    except Exception:
        return 0.0
