# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: reward.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'reward.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0creward.proto\x12\x0brlef_reward\"G\n\nTextSample\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x12\n\ncompletion\x18\x02 \x01(\t\x12\x15\n\rmetadata_json\x18\x03 \x01(\t\"9\n\rRewardRequest\x12(\n\x07samples\x18\x01 \x03(\x0b\x32\x17.rlef_reward.TextSample\"!\n\x0eRewardResponse\x12\x0f\n\x07rewards\x18\x01 \x03(\x02\x32Y\n\rRewardService\x12H\n\rEvaluateBatch\x12\x1a.rlef_reward.RewardRequest\x1a\x1b.rlef_reward.RewardResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reward_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEXTSAMPLE']._serialized_start=29
  _globals['_TEXTSAMPLE']._serialized_end=100
  _globals['_REWARDREQUEST']._serialized_start=102
  _globals['_REWARDREQUEST']._serialized_end=159
  _globals['_REWARDRESPONSE']._serialized_start=161
  _globals['_REWARDRESPONSE']._serialized_end=194
  _globals['_REWARDSERVICE']._serialized_start=196
  _globals['_REWARDSERVICE']._serialized_end=285
# @@protoc_insertion_point(module_scope)
