"""
reward.py — Core Execution Sandbox for RLEF-Code (CORRECTED)

Acts purely as the environment physics engine.
Calculates raw execution pass rates and evaluates generated test validity.
Reward shaping (step credits, multi-turn penalties) is handled upstream by train_agent.py.

FIXES vs. previous version
--------------------------
1. fn_name (call-based) problems are now actually executed and compared against
   the function's return value. Previously they scored 0 unconditionally.
2. Output normalization: APPS `input_output.json` frequently stores each output
   as a *list* (e.g. ["6"] or [["a","b"]]). The old `str(x)` cast turned ["6"]
   into the literal string "['6']", which never matched. We now flatten/join
   list-typed cases before comparison.
3. Stdin-script problems keep working (verified): top-level and __main__-guarded
   scripts both run under exec with __name__ == "__main__" set explicitly so the
   guard behaves like a real `python file.py` invocation.
4. A __main__ self-test validates the harness against known-correct solutions so
   you can prove the executor is sane before spending GPU time.
"""

import json
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass

# ── 1. Data Structures ────────────────────────────────────────────────────────


@dataclass
class ExecutionResult:
    passed: int
    total: int
    pass_rate: float
    final_reward: float  # mirrors pass_rate; kept for dataclass compatibility
    error_types: list[str]


# ── 2. Native Subprocess Isolation ────────────────────────────────────────────


def _native_execute(code_str: str, timeout: int = 10) -> tuple[bool, str, str]:
    """Runs code in an isolated subprocess. Uses a temp file to bypass the Linux
    command-line argument length limit (E2BIG) for large programs."""
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".py", delete=False, encoding="utf-8"
    ) as f:
        f.write(code_str)
        temp_file_path = f.name
    try:
        res = subprocess.run(
            ["python3", temp_file_path],
            capture_output=True,
            text=True,
            timeout=timeout,
        )
        return res.returncode == 0, res.stdout, res.stderr
    except subprocess.TimeoutExpired:
        return False, "", "Timeout"
    finally:
        if os.path.exists(temp_file_path):
            os.remove(temp_file_path)


def _classify_error(stderr: str) -> str:
    s = stderr.lower()
    if "syntaxerror" in s:
        return "SyntaxError"
    if "timeout" in s:
        return "Timeout"
    if "assertionerror" in s:
        return "AssertionError"
    if "indexerror" in s:
        return "IndexError"
    if "recursionerror" in s:
        return "RecursionError"
    return "RuntimeError"


# ── 3. Output / input normalization ───────────────────────────────────────────


def _normalize_io_item(x) -> str:
    """Normalize one APPS input/output entry into a canonical string.

    APPS stores entries inconsistently: as a plain string, as a list of lines,
    or as a nested list. We flatten lists into whitespace-joined tokens so that
    token-level comparison behaves the same regardless of storage shape.
    """
    if isinstance(x, str):
        return x
    if isinstance(x, (list, tuple)):
        # Recursively flatten; join with whitespace so token comparison is stable.
        return " ".join(_normalize_io_item(e) for e in x)
    return str(x)


def _tokens_match(produced: str, expected: str) -> bool:
    """Whitespace/trailing-insensitive token comparison (the APPS convention)."""
    return produced.strip().split() == expected.strip().split()


# ── 4. Test Verification (anti-hallucination check for <edge_cases>) ───────────


def verify_generated_tests(
    test_code: str, model_code: str, fn_name: str | None = None
) -> float:
    """
    Evaluates the <edge_cases> block generated by the model.
      1. Tests must PASS when run alongside the actual code.
      2. Tests must FAIL when run alongside a dummy function.

    NOTE: This is only meaningful for fn_name (call-based) problems, where the
    model's asserts call a known function name. For stdin problems there is no
    reliable dummy to sabotage, so we skip (return 0.0) rather than emit noise.
    """
    if not test_code or "assert " not in test_code:
        return 0.0
    if not fn_name:
        # No stable symbol to sabotage -> the dummy check is meaningless. Skip.
        return 0.0

    # Attempt 1: real code + tests must pass
    real_env = f"{model_code}\n\n{test_code}"
    real_success, _, _ = _native_execute(real_env, timeout=5)
    if not real_success:
        return -0.1  # tests fail on the model's own code

    # Attempt 2: dummy function must make the tests fail
    dummy = f"def {fn_name}(*args, **kwargs):\n    return None\n\n{test_code}"
    dummy_success, _, _ = _native_execute(dummy, timeout=5)
    if dummy_success:
        return -0.15  # generic/vacuous tests that pass against anything

    return 0.15  # mathematically discriminating tests


# ── 5. Harness builders ───────────────────────────────────────────────────────


def _build_stdin_harness(code: str, inputs: list[str], outputs: list[str]) -> str:
    """Harness for stdin/stdout problems. Runs the user program once per test
    case with __name__ == '__main__' so guarded scripts execute normally."""
    return "\n".join(
        [
            "import sys, io, builtins, math, collections, itertools, functools, heapq, bisect",
            "sys.setrecursionlimit(200000)",
            "user_code = " + repr(code),
            "all_inputs = " + repr(inputs),
            "all_outputs = " + repr(outputs),
            "passed_count = 0",
            "for inp, expected in zip(all_inputs, all_outputs):",
            "    sys.stdin = io.StringIO(inp if inp.endswith('\\n') else inp + '\\n')",
            "    builtins.input = lambda *a, **kw: sys.stdin.readline().rstrip('\\n')",
            "    old_stdout = sys.stdout",
            "    sys.stdout = captured = io.StringIO()",
            "    g = {",
            "        '__name__': '__main__',",
            "        'sys': sys, 'io': io, 'builtins': builtins, 'math': math,",
            "        'collections': collections, 'itertools': itertools,",
            "        'functools': functools, 'heapq': heapq, 'bisect': bisect,",
            "    }",
            "    try:",
            "        exec(user_code, g)",
            "        # If top-level execution already produced output (plain script",
            "        # or __main__-guarded script), do NOT call main()/solve() again",
            "        # or we consume stdin twice and hit EOF on the second run.",
            "        if not captured.getvalue().strip():",
            "            if 'main' in g and callable(g['main']): g['main']()",
            "            elif 'solve' in g and callable(g['solve']): g['solve']()",
            "    except SystemExit:",
            "        pass",
            "    except Exception:",
            "        sys.stdout = old_stdout",
            "        continue",
            "    sys.stdout = old_stdout",
            "    produced = captured.getvalue().strip().split()",
            "    if produced == expected.strip().split():",
            "        passed_count += 1",
            "print(f'RLEF_PASSED: {passed_count}')",
        ]
    )


def _build_fncall_harness(code: str, fn_name: str, inputs: list, outputs: list) -> str:
    """Harness for call-based problems. Each `inputs[i]` is the argument list for
    one call; compares the function's return value (token-normalized) against
    `outputs[i]`. This is the path that was completely missing before."""
    return "\n".join(
        [
            "import sys, io, math, collections, itertools, functools, heapq, bisect, json",
            "sys.setrecursionlimit(200000)",
            "user_code = " + repr(code),
            "all_inputs = " + repr(inputs),
            "all_outputs = " + repr(outputs),
            "fn_name = " + repr(fn_name),
            "g = {'__name__': '__main__'}",
            "passed_count = 0",
            "try:",
            "    exec(user_code, g)",
            "except Exception:",
            "    print('RLEF_PASSED: 0'); sys.exit(0)",
            "fn = g.get(fn_name)",
            "if not callable(fn):",
            "    print('RLEF_PASSED: 0'); sys.exit(0)",
            "def _canon(v):",
            "    if isinstance(v, str): return v.strip().split()",
            "    if isinstance(v, (list, tuple)):",
            "        out = []",
            "        for e in v: out.extend(_canon(e))",
            "        return out",
            "    return [str(v)]",
            "for args, expected in zip(all_inputs, all_outputs):",
            "    call_args = args if isinstance(args, list) else [args]",
            "    try:",
            "        ret = fn(*call_args)",
            "    except Exception:",
            "        continue",
            "    if _canon(ret) == _canon(expected):",
            "        passed_count += 1",
            "print(f'RLEF_PASSED: {passed_count}')",
        ]
    )


# ── 6. Main Execution Sandbox ─────────────────────────────────────────────────


def execution_reward(
    code: str,
    inputs: list,
    outputs: list,
    fn_name: str | None = None,
    **kwargs,  # absorbs legacy args like `current_turn` / `shaped`
) -> ExecutionResult:
    """Compile+run generated code against hidden tests; return linear pass rate.

    Routes to the call-based harness when `fn_name` is provided, otherwise the
    stdin/stdout harness.
    """
    # Parse JSON-encoded strings if a caller passed them through raw.
    if isinstance(inputs, str):
        try:
            inputs = json.loads(inputs)
        except Exception:
            inputs = [inputs]
    if isinstance(outputs, str):
        try:
            outputs = json.loads(outputs)
        except Exception:
            outputs = [outputs]

    total_cases = len(inputs) if inputs else 0
    if total_cases == 0 or not code or not code.strip():
        return ExecutionResult(0, 0, 0.0, 0.0, ["SyntaxError"])

    if fn_name:
        # Call-based: keep raw arg structure; only normalize expected outputs
        # inside the harness via _canon. Do NOT str()-flatten inputs here.
        harness = _build_fncall_harness(code, fn_name, inputs, outputs)
    else:
        norm_inputs = [_normalize_io_item(x) for x in inputs]
        norm_outputs = [_normalize_io_item(x) for x in outputs]
        harness = _build_stdin_harness(code, norm_inputs, norm_outputs)

    success, stdout, stderr = _native_execute(harness, timeout=15)

    passed = 0
    error_types: list[str] = []
    m = re.search(r"RLEF_PASSED:\s*(\d+)", stdout)
    if m:
        passed = int(m.group(1))
        failed = total_cases - passed
        if failed > 0:
            error_types = ["WrongOutput"] * failed
    else:
        error_types = [_classify_error(stderr)] * total_cases

    pass_rate = passed / total_cases if total_cases > 0 else 0.0
    return ExecutionResult(
        passed=passed,
        total=total_cases,
        pass_rate=pass_rate,
        final_reward=pass_rate,
        error_types=error_types,
    )


# ── 7. Self-test: prove the harness is sane BEFORE any GPU spend ───────────────


def _self_test() -> None:
    """Run known-correct solutions through the harness. All should score 1.0.
    If any of these fail, the executor is still lying and training is pointless."""
    checks = []

    # 1. Plain top-level stdin script
    checks.append(
        (
            "toplevel_stdin",
            execution_reward(
                "n=int(input())\nprint(n*2)",
                ["5", "10", "0"],
                ["10", "20", "0"],
            ).pass_rate,
        )
    )

    # 2. __main__-guarded stdin script
    checks.append(
        (
            "guarded_stdin",
            execution_reward(
                "def solve():\n    n=int(input())\n    print(n*2)\n\nif __name__=='__main__':\n    solve()",
                ["5", "10"],
                ["10", "20"],
            ).pass_rate,
        )
    )

    # 3. Multi-line stdin
    checks.append(
        (
            "multiline_stdin",
            execution_reward(
                "n=int(input())\narr=list(map(int,input().split()))\nprint(sum(arr))",
                ["3\n1 2 3"],
                ["6"],
            ).pass_rate,
        )
    )

    # 4. List-typed outputs (the silent killer)
    checks.append(
        (
            "list_typed_output",
            execution_reward(
                "n=int(input())\nprint(n*2)",
                ["5"],
                [["10"]],  # output stored as a list
            ).pass_rate,
        )
    )

    # 5. fn_name call-based problem
    checks.append(
        (
            "fn_call_based",
            execution_reward(
                "def double_it(x):\n    return x * 2",
                [[5], [0], [-3]],  # each entry is an arg list
                [10, 0, -6],
                fn_name="double_it",
            ).pass_rate,
        )
    )

    # 6. A WRONG solution must NOT score 1.0 (guards against false positives)
    checks.append(
        (
            "wrong_solution_should_fail",
            execution_reward(
                "n=int(input())\nprint(n+1)",
                ["5", "10"],
                ["10", "20"],
            ).pass_rate,
        )
    )

    print("=== reward.py self-test ===")
    ok = True
    for name, rate in checks:
        if name == "wrong_solution_should_fail":
            good = rate < 1.0
        else:
            good = rate == 1.0
        ok = ok and good
        print(f"  [{'PASS' if good else 'FAIL'}] {name}: pass_rate={rate:.3f}")
    print("=== ALL GOOD ===" if ok else "=== HARNESS BROKEN — DO NOT TRAIN ===")


if __name__ == "__main__":
    _self_test()
