"""
reward.py — Core Execution Sandbox for RLEF-Code

Acts purely as the environment physics engine.
Calculates raw execution pass rates and evaluates generated test validity.
Reward shaping (step credits, multi-turn penalties) is handled upstream by train_agent.py.
"""

import json
import os
import re
import subprocess
import tempfile
from dataclasses import dataclass

# ── 1. Data Structures ────────────────────────────────────────────────────────


@dataclass
class ExecutionResult:
    passed: int
    total: int
    pass_rate: float
    final_reward: float  # Kept for dataclass compatibility, mirrors pass_rate
    error_types: list[str]


# ── 2. Native Subprocess Isolation ────────────────────────────────────────────


def _native_execute(code_str: str, timeout: int = 2) -> tuple[bool, str, str]:
    """Runs code in an isolated subprocess to prevent master thread crashes.
    Uses a temporary file to bypass Linux OS command-line argument limits (E2BIG).
    """
    # 1. Write the massive string to a secure temporary file
    with tempfile.NamedTemporaryFile(mode="w", suffix=".py", delete=False) as f:
        f.write(code_str)
        temp_file_path = f.name

    try:
        # 2. Run the file directly (bypassing the Linux argument length limit)
        res = subprocess.run(
            ["python3", temp_file_path], capture_output=True, text=True, timeout=timeout
        )
        return res.returncode == 0, res.stdout, res.stderr
    except subprocess.TimeoutExpired:
        return False, "", "Timeout"
    finally:
        # 3. Always clean up the file immediately so you don't fill up the hard drive
        if os.path.exists(temp_file_path):
            os.remove(temp_file_path)


def _classify_error(stderr: str) -> str:
    stderr = stderr.lower()
    if "syntaxerror" in stderr:
        return "SyntaxError"
    if "timeout" in stderr:
        return "Timeout"
    if "assertionerror" in stderr:
        return "AssertionError"
    if "indexerror" in stderr:
        return "IndexError"
    return "RuntimeError"


# ── 3. Test Verification (The True/False Anti-Hallucination Check) ────────────


def verify_generated_tests(
    test_code: str, model_code: str, fn_name: str = None
) -> float:
    """
    Evaluates the <edge_cases> block generated by the model.
    1. Tests must PASS when run alongside the actual code.
    2. Tests must FAIL when run alongside a dummy function.
    """
    if not test_code or "assert " not in test_code:
        return 0.0

    # Attempt 1: Real Code
    real_env_code = f"{model_code}\n\n{test_code}"
    real_success, _, _ = _native_execute(real_env_code, timeout=2)

    if not real_success:
        return -0.1  # The tests failed on their own code

    # Attempt 2: Dummy Function
    target_fn = fn_name if fn_name else "solve"
    dummy_code = f"def {target_fn}(*args, **kwargs): return False\n\n{test_code}"
    dummy_success, _, _ = _native_execute(dummy_code, timeout=2)

    if dummy_success:
        return -0.15  # Scaled penalty for hallucinating fake generic tests

    return 0.15  # Scaled reward for mathematically sound tests


# ── 4. Main Execution Sandbox ─────────────────────────────────────────────────


def execution_reward(
    code: str,
    inputs: list[str],
    outputs: list[str],
    **kwargs,  # Absorbs legacy args like `current_turn` or `shaped` from train_agent
) -> ExecutionResult:
    """
    Compiles the generated code against the hidden tests.
    Returns the raw linear pass rate.
    """
    if isinstance(inputs, str):
        try:
            inputs = json.loads(inputs)
        except Exception:
            inputs = [inputs]
    if isinstance(outputs, str):
        try:
            outputs = json.loads(outputs)
        except Exception:
            outputs = [outputs]

    inputs = [str(x) for x in inputs]
    outputs = [str(x) for x in outputs]
    total_cases = len(inputs)

    if total_cases == 0 or not code.strip():
        return ExecutionResult(0, 0, 0.0, 0.0, ["SyntaxError"])

    lines = [
        "import sys, io, builtins",
        "sys.setrecursionlimit(200000)",
        "user_code = " + repr(code),
        "all_inputs = " + repr(inputs),
        "all_outputs = " + repr(outputs),
        "passed_count = 0",
        "for inp, expected in zip(all_inputs, all_outputs):",
        "    sys.stdin = io.StringIO(str(inp) + '\\n')",
        "    builtins.input = lambda *a, **kw: sys.stdin.readline().rstrip()",
        "    old_stdout = sys.stdout",
        "    sys.stdout = captured = io.StringIO()",
        "    sandbox_globals = {'sys': sys, 'io': io, 'builtins': builtins}",
        "    try:",
        "        exec(user_code, sandbox_globals)",
        "        if 'main' in sandbox_globals: sandbox_globals['main']()",
        "        elif 'solve' in sandbox_globals: sandbox_globals['solve']()",
        "    except Exception as e:",
        "        sys.stdout = old_stdout",
        "        continue",
        "    sys.stdout = old_stdout",
        "    if captured.getvalue().strip().split() == expected.strip().split():",
        "        passed_count += 1",
        "print(f'RLEF_PASSED: {passed_count}')",
    ]

    test_env_code = "\n".join(lines)
    success, stdout, stderr = _native_execute(test_env_code, timeout=5)

    passed = 0
    error_types = []

    match = re.search(r"RLEF_PASSED:\s*(\d+)", stdout)
    if match:
        passed = int(match.group(1))
        failed = total_cases - passed
        if failed > 0:
            error_types = ["WrongOutput"] * failed
    else:
        error_types = [_classify_error(stderr)] * total_cases

    pass_rate = passed / total_cases if total_cases > 0 else 0.0

    # Return pure linear pass rate (shaping is now handled in train_agent.py)
    return ExecutionResult(
        passed=passed,
        total=total_cases,
        pass_rate=pass_rate,
        final_reward=pass_rate,
        error_types=error_types,
    )
